##
## This file was generated by Google::ProtocolBuffers (0.05_1)
## on Tue Oct 21 11:30:01 2008
##      
use strict;
use warnings;
use Google::ProtocolBuffers;
{       
    unless (My::Test::U->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'My::Test::U',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'a', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    '[a]', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    '[UFoo.a]', 11, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (My::Test::UFoo->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'My::Test::UFoo',
            [

            ],
            { 'create_accessors' => 1,  }
        );
    }

}
1;
